# Generated by Django 5.2.7 on 2025-11-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField()),
                ('category', models.CharField()),
                ('price', models.ImageField(upload_to='')),
                ('description', models.CharField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
