# Generated by Django 5.2.7 on 2025-11-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_staff_email_remove_staff_staffname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='password',
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='food',
            name='foodname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tables',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
