# Generated by Django 5.2.7 on 2025-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_id_admin_user_rename_user_id_staff_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
