# Generated by Django 5.2.7 on 2025-11-10 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_user_admin_user_id_rename_user_staff_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tables', to_field='number')),
            ],
        ),
    ]
