# Generated by Django 5.2.7 on 2025-11-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sales_waiterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
